title: Indie Testing Community
description: A friendly Slack Community for testers to come together, learn and share knowledge in a safe environment. All welcome!
remote_theme: pages-themes/cayman@v0.2.0
slack_invite_url: https://join.slack.com/t/indietestingcommunity/shared_invite/zt-263z3g39u-MCXVYyYJoKgsZx9THYT4zQ
plugins:
- jekyll-remote-theme
